version: '2'
services:
  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${PWD}/initdb.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    command: bash -c "bundle exec crono & bundle exec puma -C config/puma.rb"
    depends_on:
      - db
  nginx:
    image: nginx
    volumes_from:
      - app
    depends_on:
      - app
  db_backup:
    image: equinoxone/postgres_backup:0.1
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    environment:
      - PGUSER=docker
      - PGPASSWORD=
      - PGPORT=5432
      - PGHOST=db
      - PGDATABASE=app_database
