version: '2'
services:
  app:
    image: jmbyun/table-api:{{VERSION}}
    volumes:
      - ./file_storage:/app/public/system/
      - assets:/app/public/assets/
    env_file:
      - configs.env
  nginx:
    ports:
      - 3080:3080
    volumes:
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/usr/share/nginx/cert
    networks:
      default:
      nginx_default:
        aliases:
          - TABLE_API
volumes:
  assets:
networks:
  nginx_default:
    external: true
